[build]
# https://docs.netlify.com/configure-builds/manage-dependencies/#node-js-and-javascript
environment = { NODE_VERSION = "18", AWS_LAMBDA_JS_RUNTIME = "nodejs18.x" }

[context.production.environment]
# https://docs.netlify.com/functions/build-with-javascript/#runtime-settings
# https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html
NODE_VERSION = "18"
AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"

[context.deploy-preview.environment]
NODE_VERSION = "18"
AWS_LAMBDA_JS_RUNTIME = "nodejs18.x"
